// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHxXlfb_qSBMXx95wbGJmRCiBVmrjnNk',
    appId: '1:990124921477:web:692ccf9881e196ea75cfec',
    messagingSenderId: '990124921477',
    projectId: 'acoder-shopping',
    authDomain: 'acoder-shopping.firebaseapp.com',
    databaseURL: 'https://acoder-shopping.firebaseio.com',
    storageBucket: 'acoder-shopping.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBLwQEbE2v2ARAZstEC0wct0HtGb1cGw',
    appId: '1:990124921477:android:5e244299726b81e375cfec',
    messagingSenderId: '990124921477',
    projectId: 'acoder-shopping',
    databaseURL: 'https://acoder-shopping.firebaseio.com',
    storageBucket: 'acoder-shopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0WZnPDNMnPwCgUtYn9MMDCnCoXBKb-M',
    appId: '1:990124921477:ios:65a032550a769e0f75cfec',
    messagingSenderId: '990124921477',
    projectId: 'acoder-shopping',
    databaseURL: 'https://acoder-shopping.firebaseio.com',
    storageBucket: 'acoder-shopping.appspot.com',
    androidClientId: '990124921477-iasokshmg06jh2hlecfqvnvlbdrl65sr.apps.googleusercontent.com',
    iosClientId: '990124921477-curp3aj5s5cke78a7266mouea61s1hp3.apps.googleusercontent.com',
    iosBundleId: 'com.serviceaccess.serviceAdmin',
  );
}
